name: Test

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 14
          - 16
          - 17
          - 18

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
      REF: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ matrix.os }}-${{ matrix.node-version }}-
            node-modules-${{ matrix.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true' }}
        run: npm i --no-fund

      - name: Check code styles
        run: npm run lint

      - name: Build for CommonJS
        run: npm run build
